"""Add instancia to users table

Revision ID: 04e6c60b14a2
Revises: 692d4dc06f5f
Create Date: 2026-05-03 17:02:45.234130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04e6c60b14a2'
down_revision: Union[str, Sequence[str], None] = '692d4dc06f5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('instancia', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'instancia')
    # ### end Alembic commands ###
