"""Initial migration

Revision ID: 692d4dc06f5f
Revises: 
Create Date: 2026-05-01 15:55:56.529356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '692d4dc06f5f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('whatsapp', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('dia_vencimento_cartao', sa.Integer(), nullable=True),
    sa.Column('limite_mensal', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('whatsapp')
    )
    op.create_table('conversas_zap',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTENTE', name='role'), nullable=False),
    sa.Column('conteudo', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('numero_parcelas', sa.Integer(), nullable=False),
    sa.Column('data_compra', sa.DateTime(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parcelas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transacao_id', sa.Integer(), nullable=False),
    sa.Column('numero_parcela', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data_vencimento', sa.DateTime(), nullable=False),
    sa.Column('pago', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['transacao_id'], ['transacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parcelas')
    op.drop_table('transacoes')
    op.drop_table('conversas_zap')
    op.drop_table('users')
    # ### end Alembic commands ###
